---
- name: "netfilter | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "netfilter | Include packages tasks"
  ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "hostvars[inventory_hostname]['netfilter'] is defined"
    - "hostvars[inventory_hostname]['netfilter'] != ''"
    - "hostvars[inventory_hostname]['netfilter'] |
       community.general.json_query(vars['netfilter_install_package']) is
       defined"
    - "hostvars[inventory_hostname]['netfilter'] |
       community.general.json_query(vars['netfilter_install_package']) ==
       'true'"
  vars:
    netfilter_install_package: "[] | map(&install_package || 'false', @) | [0]"
- name: "netfilter | Include ipset deployment tasks"
  ansible.builtin.include_tasks:
    file: "deploy_ipset.yml"
  when:
    - "vars['netfilter_settings_ipset'] is defined"
    - "vars['netfilter_settings_ipset'] != []"
- name: "netfilter | Include iptables deployment tasks"
  ansible.builtin.include_tasks:
    file: "deploy_iptables.yml"
  when:
    - "vars['netfilter_settings_iptables'] is defined"
    - "vars['netfilter_settings_iptables'] != []"
- name: "netfilter | Include arptables deployment tasks"
  ansible.builtin.include_tasks:
    file: "deploy_arptables.yml"
  when:
    - "vars['netfilter_settings_arptables'] is defined"
    - "vars['netfilter_settings_arptables'] != []"
