---
- include: pre_requisite.yml
- include: packages.yml
  when:
  - "hostvars[inventory_hostname]['netfilter_install_package'] is defined"
  - "hostvars[inventory_hostname]['netfilter_install_package'] != ''"
- include: deploy_ipset.yml
  when:
  - "vars['netfilter_ipset'] is defined"
- include: deploy_iptables.yml
  when:
  - "vars['netfilter_iptables'] is defined"
