---
- include_tasks: pre_requisite.yml
- include_tasks: packages.yml
  when:
  - "hostvars[inventory_hostname]['netfilter_install_package'] is defined"
  - "hostvars[inventory_hostname]['netfilter_install_package'] != ''"
- include_tasks: deploy_ipset.yml
  when:
  - "vars['netfilter_ipset'] is defined"
- include_tasks: deploy_iptables.yml
  when:
  - "vars['netfilter_iptables'] is defined"
