---
- name: netfilter | Install the required packages in Redhat derivatives
  yum:
    name: "{{ item }}"
    state: "installed"
  loop: "{{ hostvars[inventory_hostname]['netfilter_packages'] }}"
  when:
  - "hostvars[inventory_hostname]['ansible_os_family'] == 'RedHat'"
- name: netfilter | Install the required packages in Debian derivatives
  apt:
    name: "{{ item }}"
    state: "installed"
    update_cache: "yes"
  loop: "{{ hostvars[inventory_hostname]['netfilter_packages'] }}"
  when:
  - "hostvars[inventory_hostname]['ansible_os_family'] == 'Debian'"
- name: netfilter | Install the required packages in ArchLinux derivatives
  pacman:
    name: "{{ item }}"
    state: "installed"
    update_cache: "yes"
  loop: "{{ hostvars[inventory_hostname]['netfilter_packages'] }}"
  when:
  - "hostvars[inventory_hostname]['ansible_os_family'] == 'Archlinux'"
