---
- name: netfilter | Add the OS specific variables
  include_vars: "{{
    hostvars[inventory_hostname]['ansible_os_family'] + '.yml' }}"
- name: netfilter | Set local facts
  ansible.builtin.set_fact:
    netfilter_ipset: "{{ hostvars[inventory_hostname]['netfilter'] |
      community.general.json_query('[].netfilter_settings[].ipset[]') }}"
    netfilter_iptables: "{{ hostvars[inventory_hostname]['netfilter'] |
      community.general.json_query('[].netfilter_settings[].iptables[]') }}"
    netfilter_arptables: "{{ hostvars[inventory_hostname]['netfilter'] |
      community.general.json_query('[].netfilter_settings[].arptables[]') }}"
  when:
  - "hostvars[inventory_hostname]['netfilter'] is defined"
  - "hostvars[inventory_hostname]['netfilter'] != ''"
