---
- name: Restart ipset
  service:
    name: "{{ hostvars[inventory_hostname]['netfilter_ipset_service'] }}"
    state: "restarted"
  when:
  - "hostvars[inventory_hostname]['netfilter_ipset_restart'] is defined"
  - "hostvars[inventory_hostname]['netfilter_ipset_restart'] == 'true'"
- name: Restart iptables
  service:
    name: "{{ hostvars[inventory_hostname]['netfilter_iptables_service'] }}"
    state: "restarted"
  when:
  - "hostvars[inventory_hostname]['netfilter_iptables_restart'] is defined"
  - "hostvars[inventory_hostname]['netfilter_iptables_restart'] == 'true'"
